# Generated by Django 2.1.5 on 2019-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dop',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
