# Generated by Django 2.1.5 on 2019-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_dop'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
