# Generated by Django 2.2.7 on 2019-11-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dp',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
