# Generated by Django 2.2.7 on 2019-11-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_dp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='dp',
            new_name='cover',
        ),
    ]
