# Generated by Django 2.2.7 on 2019-11-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191122_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='dop',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='hobbies',
            new_name='mobileno',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='percentage1',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='percentage2',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='percentage3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='skills',
        ),
    ]
