# Generated by Django 2.2.7 on 2019-11-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191122_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='softwareskills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
