# Generated by Django 2.2.7 on 2019-11-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_softwareskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='programmingskills',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
